const ARENA_RADIUS = 18;
const ROBOT_SPEED = 12;
const MOVE_ACCEL = 14;
const MOVE_DAMPING = 4.5;
const ROTATE_SPEED = Math.PI;
const ROTATE_ACCEL = 10;
const ROTATE_DAMPING = 6;
const ROBOT_COLLISION_RADIUS = 2.1;
const COLLISION_DISTANCE = ROBOT_COLLISION_RADIUS * 2;
const ROUND_LIMIT = 5;
const WIN_SCORE = 3;
const GAME2_ARENA_RADIUS = 30;
const TURRET_LIMIT = Math.PI / 3;
const DRIVER_CAMERA_HEIGHT = 26;
const DRIVER_CAMERA_DISTANCE = 28;
const DRIVER_FOV = 40;
const MAIN_CAMERA_MARGIN = 1.05;
const ARENA_BOUNDARY_PADDING = 0.2;
const RIM_HALF_WIDTH = 0.25;
const FLOOR_TEXTURE_SIZE = 1024;
const GAME2_DRIVER_SPEED = 9;
const GAME2_ROTATE_SPEED = Math.PI * 0.85;
const GAME2_TURRET_SPEED = Math.PI;
const GAME2_FIRE_RATE = 0.22;
const GAME2_ENEMY_SPEED = 4.5;
const GAME2_SPAWN_MIN = 1.3;
const GAME2_SPAWN_MAX = 1.9;
const GAME2_SPAWN_RADIUS = GAME2_ARENA_RADIUS + 8;
const GAME2_BULLET_LIMIT = GAME2_ARENA_RADIUS + 6;
module.exports = {
  ARENA_RADIUS,
  ROBOT_SPEED,
  MOVE_ACCEL,
  MOVE_DAMPING,
  ROTATE_SPEED,
  ROTATE_ACCEL,
  ROTATE_DAMPING,
  ROBOT_COLLISION_RADIUS,
  COLLISION_DISTANCE,
  ROUND_LIMIT,
  WIN_SCORE,
  GAME2_ARENA_RADIUS,
  TURRET_LIMIT,
  DRIVER_CAMERA_HEIGHT,
  DRIVER_CAMERA_DISTANCE,
  DRIVER_FOV,
  MAIN_CAMERA_MARGIN,
  ARENA_BOUNDARY_PADDING,
  RIM_HALF_WIDTH,
  FLOOR_TEXTURE_SIZE,
  GAME2_DRIVER_SPEED,
  GAME2_ROTATE_SPEED,
  GAME2_TURRET_SPEED,
  GAME2_FIRE_RATE,
  GAME2_ENEMY_SPEED,
  GAME2_SPAWN_MIN,
  GAME2_SPAWN_MAX,
  GAME2_SPAWN_RADIUS,
  GAME2_BULLET_LIMIT,
};
